In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/My Drive/AML_Final_report')

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ast

In [ ]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
train.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970

In [ ]:
train.dtypes

id                         int64
belongs_to_collection     object
budget                     int64
genres                    object
homepage                  object
imdb_id                   object
original_language         object
original_title            object
overview                  object
popularity               float64
poster_path               object
production_companies      object
production_countries      object
release_date              object
runtime                  float64
spoken_languages          object
status                    object
tagline                   object
title                     object
Keywords                  object
cast                      object
crew                      object
revenue                    int64
dtype: object

# Num columns

In [ ]:
train.budget = train.budget.replace(0,np.nan)
test.budget = test.budget.replace(0,np.nan)

train.budget = train.budget.apply(lambda x: np.log(x))
test.budget = test.budget.apply(lambda x: np.log(x))

train.revenue = train.revenue.apply(lambda x: np.log(x))

train.runtime.fillna(list(train.runtime.describe())[1], inplace = True)
test.runtime.fillna(list(test.runtime.describe())[1], inplace = True)
train.budget.fillna(list(train.budget.describe())[1], inplace = True)
test.budget.fillna(list(test.budget.describe())[1], inplace = True)

In [ ]:
y = train.revenue

In [ ]:
train.drop(columns=['id', 'belongs_to_collection', 'homepage', 'tagline', 'poster_path', 'imdb_id', 'original_title', 'title', 'revenue'], inplace=True)
test.drop(columns=['id', 'belongs_to_collection', 'homepage', 'tagline', 'poster_path', 'imdb_id', 'original_title', 'title'], inplace=True)

## Data Preprocessing

### Dictionary Columns

In [ ]:
def json_change(k):
    if type(k) == str:
        return ast.literal_eval(k)
    else:
        return k

In [ ]:
# Correcting the format of dictionary columns
dic_cols = ['genres', 'production_companies', 'production_countries',
            'spoken_languages', 'Keywords', 'cast', 'crew']

for c in dic_cols:
    train[c] = train[c].apply(lambda x: json_change(x))
    test[c] = test[c].apply(lambda x: json_change(x))

In [ ]:
train

,budget,genres,original_language,overview,popularity,production_companies,production_countries,release_date,runtime,spoken_languages,status,Keywords,cast,crew
0,16.454568,"[{'id': 35, 'name': 'Comedy'}]",en,"When Lou, who has become the ""father of the In...",6.575393,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de..."
1,17.504390,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en,Mia Thermopolis is now a college graduate and ...,8.248895,"[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'iso_3166_1': 'US', 'name': 'United States o...",8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de..."
2,15.009433,"[{'id': 18, 'name': 'Drama'}]",en,"Under the direction of a ruthless instructor, ...",64.299990,"[{'name': 'Bold Films', 'id': 2266}, {'name': ...","[{'iso_3166_1': 'US', 'name': 'United States o...",10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de..."
3,13.997832,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",hi,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,NaN,"[{'iso_3166_1': 'IN', 'name': 'India'}]",3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de..."
4,16.284763,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",ko,Marine Boy is the story of a former national s...,1.148070,NaN,"[{'iso_3166_1': 'KR', 'name': 'South Korea'}]",2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,16.284763,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",en,Military men Rock Reilly and Eddie Devane are ...,9.853270,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de..."
2996,16.284763,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",sv,Three girls in 1980s Stockholm decide to form ...,3.727996,"[{'name': 'Memfis Film', 'id': 321}, {'name': ...","[{'iso_3166_1': 'DK', 'name': 'Denmark'}, {'is...",3/28/13,102.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de..."
2997,17.989898,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",en,"Samantha Caine, suburban homemaker, is the ide...",14.482345,"[{'name': 'New Line Cinema', 'id': 12}, {'name...","[{'iso_3166_1': 'US', 'name': 'United States o...",10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de..."
2998,17.553180,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",en,Reuben Feffer is a guy who's spent his entire ...,15.725542,"[{'name': 'Jersey Films', 'id': 216}, {'name':...","[{'iso_3166_1': 'US', 'name': 'United States o...",1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de..."
2999,17.370859,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",en,A young man sets out to uncover the truth abou...,10.512109,"[{'name': 'Lions Gate Films', 'id': 35}, {'nam...","[{'iso_3166_1': 'US', 'name': 'United States o...",9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de..."

In [ ]:
# Creating lists out of dictionary
from tqdm.auto import tqdm

train['character'] = '0'
test['character'] = '0'
for c in dic_cols:
    # Dev data
    for i in range(len(train)):
        temp = []
        character = []
        name = []
        try:
            for dic in train[c].iloc[i]:
                if c == 'production_countries':
                    temp.append(dic['iso_3166_1'])
                elif c == 'spoken_languages':
                    temp.append(dic['iso_639_1'])
                elif c == 'cast':
                    character.append(dic['character'])
                    temp.append(dic['name'])
                else:
                    temp.append(dic['name'])
            train[c].iloc[i] = temp
            if c == 'cast':
                train['character'].iloc[i] = character
        except:
            continue
    
    # test data
    for i in range(len(test)):
        temp = []
        character = []
        name = []
        try:
            for dic in test[c].iloc[i]:
                if c == 'production_countries':
                    temp.append(dic['iso_3166_1'])
                elif c == 'spoken_languages':
                    temp.append(dic['iso_639_1'])
                elif c == 'cast':
                    character.append(dic['character'])
                    temp.append(dic['name'])
                else:
                    temp.append(dic['name'])
            test[c].iloc[i] = temp
            if c == 'cast':
                test['character'].iloc[i] = character
        except:
            continue

C:\Users\xiaorui\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [ ]:
train

,budget,genres,original_language,overview,popularity,production_companies,production_countries,release_date,runtime,spoken_languages,status,Keywords,cast,crew,character
0,16.454568,[Comedy],en,"When Lou, who has become the ""father of the In...",6.575393,"[Paramount Pictures, United Artists, Metro-Gol...",[US],2/20/15,93.0,[en],Released,"[time travel, sequel, hot tub, duringcreditsst...","[Rob Corddry, Craig Robinson, Clark Duke, Adam...","[Kelly Cantley, Steve Pink, Josh Heald, Josh H...","[Lou, Nick, Jacob, Adam Jr., Hot Tub Repairman..."
1,17.504390,"[Comedy, Drama, Family, Romance]",en,Mia Thermopolis is now a college graduate and ...,8.248895,[Walt Disney Pictures],[US],8/6/04,113.0,[en],Released,"[coronation, duty, marriage, falling in love]","[Anne Hathaway, Julie Andrews, H√©ctor Elizond...","[Garry Marshall, Charles Minsky, John Debney, ...","[Mia Thermopolis, Queen Clarisse Renaldi, Joe,..."
2,15.009433,[Drama],en,"Under the direction of a ruthless instructor, ...",64.299990,"[Bold Films, Blumhouse Productions, Right of W...",[US],10/10/14,105.0,[en],Released,"[jazz, obsession, conservatory, music teacher,...","[Miles Teller, J.K. Simmons, Melissa Benoist, ...","[Terri Taylor, Richard Henderson, Jeffrey Stot...","[Andrew Neimann, Terence Fletcher, Nicole, Rya..."
3,13.997832,"[Thriller, Drama]",hi,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,NaN,[IN],3/9/12,122.0,"[en, hi]",Released,"[mystery, bollywood, police corruption, crime,...","[Vidya Balan, Nawazuddin Siddiqui, Parambrata ...","[Sujoy Ghosh, Sujoy Ghosh, Sujoy Ghosh]","[Vidya Bagchi, , , , , , ]"
4,16.284763,"[Action, Thriller]",ko,Marine Boy is the story of a former national s...,1.148070,NaN,[KR],2/5/09,118.0,[ko],Released,NaN,"[Kim Kang-woo, Jo Jae-hyeon, Park Si-yeon, Kim...","[Jong-seok Yoon, Jong-seok Yoon]","[Chun-soo, Company president Kang, Yu-ri, Comp..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,16.284763,"[Comedy, Romance]",en,Military men Rock Reilly and Eddie Devane are ...,9.853270,"[Warner Bros., Morgan Creek Productions]",[US],4/22/94,102.0,[en],Released,"[prison, sex, handcuffs, waitress, fight, fire...","[Tom Berenger, William McNamara, –≠—Ä–∏–∫–∞ –≠...","[Dennis Hopper, Joe Batteer, John Rice, Joe Ba...","[Rock Reilly, Eddie Devane, Toni Johnson, Howa..."
2996,16.284763,"[Drama, Music]",sv,Three girls in 1980s Stockholm decide to form ...,3.727996,"[Memfis Film, Film i Väst]","[DK, SE]",3/28/13,102.0,[sv],Released,"[sweden, punk, based on comic, all girl band, ...","[Mira Barkhammar, Mira Grosin, Liv LeMoyne, Da...","[Imor Hermann, Anna Anthony, Lukas Moodysson, ...","[Bobo, Klara, Hedvig, Klaras pappa, Kenneth, R..."
2997,17.989898,"[Crime, Action, Mystery, Thriller]",en,"Samantha Caine, suburban homemaker, is the ide...",14.482345,"[New Line Cinema, Forge, The Steve Tisch Company]",[US],10/11/96,120.0,[en],Released,"[assassination, amnesia, hostage, chase, dark ...","[Geena Davis, Samuel L. Jackson, Yvonne Zima, ...","[Renny Harlin, Shane Black, Stephanie Austin, ...","[Samantha Caine / Charly Baltimore, Mitch Hene..."
2998,17.553180,"[Comedy, Romance]",en,Reuben Feffer is a guy who's spent his entire ...,15.725542,"[Jersey Films, Loofah Productions]",[US],1/16/04,90.0,[en],Released,"[beach, honeymoon, bride, chance, risk, relati...","[Ben Stiller, Jennifer Aniston, Philip Seymour...","[Danny DeVito, Seamus McGarvey, Nick Moore, Th...","[Reuben Feffer, Polly Prince, Sandy Lyle, Lisa..."
2999,17.370859,"[Thriller, Action, Mystery]",en,A young man sets out to uncover the truth abou...,10.512109,"[Lions Gate Films, Vertigo Entertainment, Goth...",[US],9/22/11,106.0,[en],Released,"[cia, airport, hero, fight, kidnapping, time b...","[Taylor Lautner, Lily Collins, Alfred Molina, ...","[Joseph Middleton, Ed Shearmur, John Singleton...","[Nathan Harper, Karen Murphy, Frank Burton, Ke..."

### Date Columns

In [ ]:
for i in range(len(train)):
    date = train.release_date.iloc[i].split('/')
    if int(date[2]) >= 20:
        to_fill = date[0]+'/'+date[1]+'/19'+date[2]
        train.release_date.iloc[i] = to_fill
    else:
        to_fill = date[0]+'/'+date[1]+'/20'+date[2]
        train.release_date.iloc[i] = to_fill

for i in range(len(test)):
    try:
        date = test.release_date.iloc[i].split('/')
        if int(date[2]) >= 20:
            to_fill = date[0]+'/'+date[1]+'/19'+date[2]
            test.release_date.iloc[i] = to_fill
        else:
            to_fill = date[0]+'/'+date[1]+'/20'+date[2]
            test.release_date.iloc[i] = to_fill
    except:
        continue

C:\Users\xiaorui\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [ ]:
from datetime import datetime

train.release_date = pd.to_datetime(train.release_date)
test.release_date = pd.to_datetime(test.release_date)
reference = datetime(2020,1,1)

In [ ]:
train['days_since_release'] = (reference - train.release_date).dt.days
test['days_since_release'] = (reference - test.release_date).dt.days

In [ ]:
train['weekday'] = 0
train['day'] = 0
train['month'] = 0
train['year'] = 0

test['weekday'] = 0
test['day'] = 0
test['month'] = 0
test['year'] = 0

for i in range(len(train)):
    train['weekday'].iloc[i] = train.release_date[i].weekday()
    train['day'].iloc[i] = train.release_date[i].day
    train['month'].iloc[i] = train.release_date[i].month
    train['year'].iloc[i] = train.release_date[i].year
    
    
for i in range(len(test)):
    test['weekday'].iloc[i] = test.release_date[i].weekday()
    test['day'].iloc[i] = test.release_date[i].day
    test['month'].iloc[i] = test.release_date[i].month
    test['year'].iloc[i] = test.release_date[i].year

In [ ]:
train = train.drop(columns=['release_date'])
test = test.drop(columns=['release_date'])

In [ ]:
train.weekday = train.weekday.astype("category")
test.weekday = test.weekday.astype("category")

train.day = train.day.astype("category")
test.day = test.day.astype("category")

train.month = train.month.astype("category")
test.month = test.month.astype("category")

In [ ]:
train

,budget,genres,original_language,overview,popularity,production_companies,production_countries,runtime,spoken_languages,status,Keywords,cast,crew,character,days_since_release,weekday,day,month,year
0,16.454568,[Comedy],en,"When Lou, who has become the ""father of the In...",6.575393,"[Paramount Pictures, United Artists, Metro-Gol...",[US],93.0,[en],Released,"[time travel, sequel, hot tub, duringcreditsst...","[Rob Corddry, Craig Robinson, Clark Duke, Adam...","[Kelly Cantley, Steve Pink, Josh Heald, Josh H...","[Lou, Nick, Jacob, Adam Jr., Hot Tub Repairman...",1776,4,20,2,2015
1,17.504390,"[Comedy, Drama, Family, Romance]",en,Mia Thermopolis is now a college graduate and ...,8.248895,[Walt Disney Pictures],[US],113.0,[en],Released,"[coronation, duty, marriage, falling in love]","[Anne Hathaway, Julie Andrews, H√©ctor Elizond...","[Garry Marshall, Charles Minsky, John Debney, ...","[Mia Thermopolis, Queen Clarisse Renaldi, Joe,...",5626,4,6,8,2004
2,15.009433,[Drama],en,"Under the direction of a ruthless instructor, ...",64.299990,"[Bold Films, Blumhouse Productions, Right of W...",[US],105.0,[en],Released,"[jazz, obsession, conservatory, music teacher,...","[Miles Teller, J.K. Simmons, Melissa Benoist, ...","[Terri Taylor, Richard Henderson, Jeffrey Stot...","[Andrew Neimann, Terence Fletcher, Nicole, Rya...",1909,4,10,10,2014
3,13.997832,"[Thriller, Drama]",hi,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,NaN,[IN],122.0,"[en, hi]",Released,"[mystery, bollywood, police corruption, crime,...","[Vidya Balan, Nawazuddin Siddiqui, Parambrata ...","[Sujoy Ghosh, Sujoy Ghosh, Sujoy Ghosh]","[Vidya Bagchi, , , , , , ]",2854,4,9,3,2012
4,16.284763,"[Action, Thriller]",ko,Marine Boy is the story of a former national s...,1.148070,NaN,[KR],118.0,[ko],Released,NaN,"[Kim Kang-woo, Jo Jae-hyeon, Park Si-yeon, Kim...","[Jong-seok Yoon, Jong-seok Yoon]","[Chun-soo, Company president Kang, Yu-ri, Comp...",3982,3,5,2,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,16.284763,"[Comedy, Romance]",en,Military men Rock Reilly and Eddie Devane are ...,9.853270,"[Warner Bros., Morgan Creek Productions]",[US],102.0,[en],Released,"[prison, sex, handcuffs, waitress, fight, fire...","[Tom Berenger, William McNamara, –≠—Ä–∏–∫–∞ –≠...","[Dennis Hopper, Joe Batteer, John Rice, Joe Ba...","[Rock Reilly, Eddie Devane, Toni Johnson, Howa...",9385,4,22,4,1994
2996,16.284763,"[Drama, Music]",sv,Three girls in 1980s Stockholm decide to form ...,3.727996,"[Memfis Film, Film i Väst]","[DK, SE]",102.0,[sv],Released,"[sweden, punk, based on comic, all girl band, ...","[Mira Barkhammar, Mira Grosin, Liv LeMoyne, Da...","[Imor Hermann, Anna Anthony, Lukas Moodysson, ...","[Bobo, Klara, Hedvig, Klaras pappa, Kenneth, R...",2470,3,28,3,2013
2997,17.989898,"[Crime, Action, Mystery, Thriller]",en,"Samantha Caine, suburban homemaker, is the ide...",14.482345,"[New Line Cinema, Forge, The Steve Tisch Company]",[US],120.0,[en],Released,"[assassination, amnesia, hostage, chase, dark ...","[Geena Davis, Samuel L. Jackson, Yvonne Zima, ...","[Renny Harlin, Shane Black, Stephanie Austin, ...","[Samantha Caine / Charly Baltimore, Mitch Hene...",8482,4,11,10,1996
2998,17.553180,"[Comedy, Romance]",en,Reuben Feffer is a guy who's spent his entire ...,15.725542,"[Jersey Films, Loofah Productions]",[US],90.0,[en],Released,"[beach, honeymoon, bride, chance, risk, relati...","[Ben Stiller, Jennifer Aniston, Philip Seymour...","[Danny DeVito, Seamus McGarvey, Nick Moore, Th...","[Reuben Feffer, Polly Prince, Sandy Lyle, Lisa...",5829,4,16,1,2004
2999,17.370859,"[Thriller, Action, Mystery]",en,A young man sets out to uncover the truth abou...,10.512109,"[Lions Gate Films, Vertigo Entertainment, Goth...",[US],106.0,[en],Released,"[cia, airport, hero, fight, kidnapping, time b...","[Taylor Lautner, Lily Collins, Alfred Molina, ...","[Joseph Middleton, Ed Shearmur, John Singleton...","[Nathan Harper, Karen Murphy, Frank Burton, Ke...",3023,3,22,9,2011

### Additional Feature Engineering

In [ ]:
train['no_genres'] = 0 
train['no_companies'] = 0 
train['no_actors'] = 0
train['no_keywords'] = 0
train['no_countries'] = 0
train['no_crew'] = 0


for i in range(len(train)):
    try:
        train.no_genres.iloc[i] = len(train.genres.iloc[i])
    except:
        pass
    try:
        train.no_companies.iloc[i] = len(train.production_companies.iloc[i])
    except:
        pass
    try:
        train.no_actors.iloc[i] = len(train.cast.iloc[i])
    except:
        pass
    try:
        train.no_keywords.iloc[i] = len(train.Keywords.iloc[i])
    except:
        pass
    try:
        train.no_countries.iloc[i] = len(train.production_countries.iloc[i])
    except:
        pass
    try:
        train.no_crew.iloc[i] = len(train.crew.iloc[i])
    except:
        pass


test['no_genres'] = 0 
test['no_companies'] = 0 
test['no_actors'] = 0
test['no_keywords'] = 0
test['no_countries'] = 0
test['no_crew'] = 0
    
    
for i in range(len(test)):
    try:
        test.no_genres.iloc[i] = len(test.genres.iloc[i])
    except:
        pass
    try:
        test.no_companies.iloc[i] = len(test.production_companies.iloc[i])
    except:
        pass
    try:
        test.no_actors.iloc[i] = len(test.cast.iloc[i])
    except:
        pass
    try:
        test.no_keywords.iloc[i] = len(test.Keywords.iloc[i])
    except:
        pass
    try:
        test.no_countries.iloc[i] = len(test.production_countries.iloc[i])
    except:
        pass
    try:
        test.no_crew.iloc[i] = len(test.crew.iloc[i])
    except:
        pass

C:\Users\xiaorui\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [ ]:
train

,budget,genres,original_language,overview,popularity,production_companies,production_countries,runtime,spoken_languages,status,...,weekday,day,month,year,no_genres,no_companies,no_actors,no_keywords,no_countries,no_crew
0,16.454568,[Comedy],en,"When Lou, who has become the ""father of the In...",6.575393,"[Paramount Pictures, United Artists, Metro-Gol...",[US],93.0,[en],Released,...,4,20,2,2015,1,3,24,4,1,72
1,17.504390,"[Comedy, Drama, Family, Romance]",en,Mia Thermopolis is now a college graduate and ...,8.248895,[Walt Disney Pictures],[US],113.0,[en],Released,...,4,6,8,2004,4,1,20,4,1,9
2,15.009433,[Drama],en,"Under the direction of a ruthless instructor, ...",64.299990,"[Bold Films, Blumhouse Productions, Right of W...",[US],105.0,[en],Released,...,4,10,10,2014,1,3,51,12,1,64
3,13.997832,"[Thriller, Drama]",hi,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,NaN,[IN],122.0,"[en, hi]",Released,...,4,9,3,2012,2,0,7,7,1,3
4,16.284763,"[Action, Thriller]",ko,Marine Boy is the story of a former national s...,1.148070,NaN,[KR],118.0,[ko],Released,...,3,5,2,2009,2,0,4,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,16.284763,"[Comedy, Romance]",en,Military men Rock Reilly and Eddie Devane are ...,9.853270,"[Warner Bros., Morgan Creek Productions]",[US],102.0,[en],Released,...,4,22,4,1994,2,2,15,19,1,17
2996,16.284763,"[Drama, Music]",sv,Three girls in 1980s Stockholm decide to form ...,3.727996,"[Memfis Film, Film i Väst]","[DK, SE]",102.0,[sv],Released,...,3,28,3,2013,2,2,11,6,2,15
2997,17.989898,"[Crime, Action, Mystery, Thriller]",en,"Samantha Caine, suburban homemaker, is the ide...",14.482345,"[New Line Cinema, Forge, The Steve Tisch Company]",[US],120.0,[en],Released,...,4,11,10,1996,4,3,15,14,1,10
2998,17.553180,"[Comedy, Romance]",en,Reuben Feffer is a guy who's spent his entire ...,15.725542,"[Jersey Films, Loofah Productions]",[US],90.0,[en],Released,...,4,16,1,2004,2,2,26,22,1,89
2999,17.370859,"[Thriller, Action, Mystery]",en,A young man sets out to uncover the truth abou...,10.512109,"[Lions Gate Films, Vertigo Entertainment, Goth...",[US],106.0,[en],Released,...,3,22,9,2011,3,6,34,14,1,48

## Text Data

In [ ]:
# Build the corpus of the "overview"
corpus = 'corpus.txt'
with open(corpus, 'w', encoding = 'utf-8') as outfile:
    for i in range(train.shape[0]):
        line = train.iloc[i]['overview']
        outfile.write(str(line))
        outfile.write("\n")
    for i in range(test.shape[0]):
        line = test.iloc[i]['overview']
        outfile.write(str(line))
        outfile.write("\n")
outfile.close()

In [ ]:
from gensim.models import Word2Vec
def w2v(corpus_sents, save, dim, window, sg, hs, negative, min_count, workers):
    '''
    sg ({0, 1}) – Training algorithm: 1 for skip-gram; otherwise CBOW.
    hs ({0, 1}) – If 1, hierarchical softmax will be used for model training. If 0, and negative is non-zero, negative sampling will be used.
    negative (int) – If > 0, negative sampling will be used, the int for negative specifies how many “noise words” should be drawn (usually between 5-20). If set to 0, no negative sampling is used.
    min_count (int) – Ignores all words with total frequency lower than this.
    workers (int) – Use these many worker threads to train the model (=faster training with multicore machines).'''
    model = Word2Vec(corpus_sents, sg=sg, hs=hs, vector_size=dim, window=window, negative = negative, min_count=min_count, workers=workers)
    model.wv.save(save)
    print('Word2vec with window = ' + str(window) + ', dim = ' + str(dim))

In [ ]:
from gensim.models import KeyedVectors
from scipy.spatial import distance
import string

corpus_sents = [x.translate(str.maketrans('', '', string.punctuation)).strip().split() for x in open(corpus, 'r', encoding = 'utf-8').readlines()]
dim = 20
window = 2
sg = 1
hs = 0
save = str(window) + '-' + str(dim) + '-' + str(sg) + '-' + str(hs) + '.vec'
w2v(corpus_sents, save, dim, window, sg, hs, negative = 10, min_count = 1, workers = 4)
file_name = "2-20-1-0"
w2v = KeyedVectors.load(file_name + ".vec", mmap='r')

with open('vocab.txt', 'w', encoding = 'utf-8') as outfile:
    for i in range(len(w2v.index_to_key)):
        line = w2v.index_to_key[i]
        outfile.write(str(line))
        outfile.write("\n")
outfile.close()

vocab = []
lines = open("vocab.txt", 'r', encoding = 'utf-8').readlines()
for l in lines:
    vocab.append(l.strip("\n"))

model = {}
for i in range(len(vocab)):
    model[vocab[i]] = w2v[vocab[i]]

out = open("2-20-1-0" + ".txt", 'w', encoding = 'utf-8')
for v in vocab:
    if v in w2v.index_to_key:
        out.write(v)
        for x in model[v]:
            out.write(' ' + str(x))
        out.write('\n')
out.close()

Word2vec with window = 2, dim = 20

In [ ]:
def get_X(sample, word_emb, word_emb_size):
    x_t = np.zeros(word_emb_size)
    for word in sample:
        word = word.lower()
        if word in word_emb:
            x_t += word_emb[word]
    if len(sample) > 0:
        x_t /= len(sample)
    return x_t

def load_vec(path, word_emb_size):
    wv = {}
    with open(path,'r',encoding='utf8') as fr:
        for i, line in enumerate(fr):
            data = line.strip().split()
            if len(data) == word_emb_size+1:
                v = np.zeros((word_emb_size,),dtype='float32')
                for j in range(word_emb_size):
                    v[j] = float(data[j+1])
                wv[data[0].lower()] = v
    return wv

In [ ]:
for i in range(dim):
    train['overview_' + str(i)] = 0.0
word_to_embeddings = load_vec('2-20-1-0' + ".txt", dim)
for i in range(train.shape[0]):
    overview = train.iloc[i]['overview']
    if type(overview) == str:
        words = overview.translate(str.maketrans('', '', string.punctuation)).strip().split()
        sentence_embedding = get_X(words, word_to_embeddings, dim)
        for j in range(dim):
            train['overview_' + str(j)].iloc[i] = sentence_embedding[j]

C:\Users\xiaorui\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [ ]:
train

,budget,genres,original_language,overview,popularity,production_companies,production_countries,runtime,spoken_languages,status,...,overview_10,overview_11,overview_12,overview_13,overview_14,overview_15,overview_16,overview_17,overview_18,overview_19
0,16.454568,[Comedy],en,"When Lou, who has become the ""father of the In...",6.575393,"[Paramount Pictures, United Artists, Metro-Gol...",[US],93.0,[en],Released,...,0.536426,-0.192649,0.104035,-0.147556,0.419760,0.295455,0.485162,-0.307395,-0.249342,-0.583164
1,17.504390,"[Comedy, Drama, Family, Romance]",en,Mia Thermopolis is now a college graduate and ...,8.248895,[Walt Disney Pictures],[US],113.0,[en],Released,...,0.615564,-0.331844,0.157732,-0.108872,0.414449,0.251370,0.786919,-0.291683,-0.275383,-0.557952
2,15.009433,[Drama],en,"Under the direction of a ruthless instructor, ...",64.299990,"[Bold Films, Blumhouse Productions, Right of W...",[US],105.0,[en],Released,...,0.496889,-0.229673,0.206034,-0.075907,0.389914,0.220134,0.585413,-0.266572,-0.346724,-0.415035
3,13.997832,"[Thriller, Drama]",hi,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,NaN,[IN],122.0,"[en, hi]",Released,...,0.541240,-0.290496,0.174390,-0.074652,0.492653,0.190652,0.711849,-0.233447,-0.274890,-0.472324
4,16.284763,"[Action, Thriller]",ko,Marine Boy is the story of a former national s...,1.148070,NaN,[KR],118.0,[ko],Released,...,0.526499,-0.326353,0.204893,-0.027304,0.453666,0.221088,0.569022,-0.291921,-0.426123,-0.474138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,16.284763,"[Comedy, Romance]",en,Military men Rock Reilly and Eddie Devane are ...,9.853270,"[Warner Bros., Morgan Creek Productions]",[US],102.0,[en],Released,...,0.573148,-0.257770,0.187512,-0.057574,0.441214,0.258316,0.643566,-0.277964,-0.338794,-0.517095
2996,16.284763,"[Drama, Music]",sv,Three girls in 1980s Stockholm decide to form ...,3.727996,"[Memfis Film, Film i Väst]","[DK, SE]",102.0,[sv],Released,...,0.501013,-0.217894,0.164280,-0.069716,0.479765,0.226646,0.525287,-0.255386,-0.264619,-0.503847
2997,17.989898,"[Crime, Action, Mystery, Thriller]",en,"Samantha Caine, suburban homemaker, is the ide...",14.482345,"[New Line Cinema, Forge, The Steve Tisch Company]",[US],120.0,[en],Released,...,0.548795,-0.273722,0.208447,-0.030191,0.415439,0.266841,0.645974,-0.235780,-0.321746,-0.452692
2998,17.553180,"[Comedy, Romance]",en,Reuben Feffer is a guy who's spent his entire ...,15.725542,"[Jersey Films, Loofah Productions]",[US],90.0,[en],Released,...,0.525304,-0.213195,0.165135,-0.096941,0.400923,0.242246,0.586907,-0.271569,-0.287742,-0.441850
2999,17.370859,"[Thriller, Action, Mystery]",en,A young man sets out to uncover the truth abou...,10.512109,"[Lions Gate Films, Vertigo Entertainment, Goth...",[US],106.0,[en],Released,...,0.526760,-0.230847,0.190555,-0.081144,0.427070,0.218839,0.658428,-0.299528,-0.353423,-0.337437

In [ ]:
for i in range(dim):
    test['overview_' + str(i)] = 0.0
word_to_embeddings = load_vec('2-20-1-0' + ".txt", dim)
for i in range(test.shape[0]):
    overview = test.iloc[i]['overview']
    if type(overview) == str:
        words = overview.translate(str.maketrans('', '', string.punctuation)).strip().split()
        sentence_embedding = get_X(words, word_to_embeddings, dim)
        for j in range(dim):
            test['overview_' + str(j)].iloc[i] = sentence_embedding[j]

C:\Users\xiaorui\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [ ]:
test

,budget,genres,original_language,overview,popularity,production_companies,production_countries,runtime,spoken_languages,status,...,overview_10,overview_11,overview_12,overview_13,overview_14,overview_15,overview_16,overview_17,overview_18,overview_19
0,16.256171,"[Adventure, Animation, Family, Fantasy]",ja,Ash and friends (this time accompanied by newc...,3.851534,NaN,"[JP, US]",90.0,"[en, ja]",Released,...,0.514133,-0.210813,0.138380,-0.081176,0.448012,0.288231,0.528447,-0.288268,-0.294609,-0.526082
1,11.385092,"[Horror, Science Fiction]",en,When an abused wife grows to giant size becaus...,3.559789,[Woolner Brothers Pictures Inc.],[US],65.0,[en],Released,...,0.594148,-0.232524,0.174998,-0.099757,0.428025,0.256064,0.741382,-0.265915,-0.354513,-0.409917
2,16.256171,"[Comedy, Romance]",en,Good-natured astronomer Sam is devastated when...,8.085194,"[Warner Bros., Outlaw Productions (I), Miramax]",[US],100.0,[en],Released,...,0.559898,-0.262138,0.160929,-0.112417,0.402352,0.211594,0.630939,-0.243746,-0.274169,-0.435889
3,15.732433,"[Drama, War, Mystery]",fr,A mother's last wishes send twins Jeanne and S...,8.596012,"[TS Productions, Micro scope, Phi Group]","[CA, FR]",130.0,"[fr, ar, en]",Released,...,0.473570,-0.193790,0.157461,-0.062625,0.447302,0.259361,0.420734,-0.268004,-0.290535,-0.484401
4,14.508658,"[History, Documentary]",en,"In 1972, a seemingly typical shoestring budget...",3.217680,NaN,[US],92.0,[en],Released,...,0.539880,-0.245214,0.164927,-0.022686,0.448448,0.242420,0.576818,-0.274879,-0.291070,-0.606661
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4393,17.553180,[Thriller],en,A young man is plunged into a life of subterfu...,9.970359,"[Intermedia Films, DiNovi Pictures, Epsilon Mo...","[FR, US]",118.0,"[en, de, ja, la, es]",Released,...,0.505691,-0.210003,0.258301,-0.068198,0.405370,0.230554,0.560617,-0.256416,-0.358335,-0.374784
4394,16.759950,"[Action, Adventure, Comedy, Thriller]",en,"Three friends, whose lives have been drifting ...",6.046516,"[Paramount Pictures, De Line Pictures]",[US],95.0,[en],Released,...,0.509222,-0.213421,0.093606,-0.105280,0.464791,0.192495,0.668367,-0.280450,-0.298039,-0.496226
4395,16.588099,[Drama],en,"Frank Galvin is a down-on-his luck lawyer, red...",9.596883,[Twentieth Century Fox Film Corporation],[US],129.0,[en],Released,...,0.574643,-0.263006,0.166522,-0.106307,0.398686,0.187311,0.655430,-0.275110,-0.330682,-0.425411
4396,14.508658,"[Horror, Thriller]",en,"For 19-year-old Jay, fall should be about scho...",20.359336,"[Northern Lights Films, Animal Kingdom, Two Fl...",[US],100.0,[en],Released,...,0.576136,-0.283704,0.173470,-0.094721,0.436570,0.198709,0.689140,-0.254721,-0.310145,-0.541236
4397,11.066638,[Drama],fr,Twelve episodic tales in the life of a Parisia...,11.305910,"[Pathé Consortium Cinéma, Les Films de la Pléi...",[FR],85.0,[fr],Released,...,0.551771,-0.245107,0.269448,-0.000864,0.489464,0.292244,0.522991,-0.253974,-0.330809,-0.464275

In [ ]:
train.drop(columns=['overview'],inplace=True)
test.drop(columns=['overview'],inplace=True)

## Categorical Columns

In [ ]:
features_choose_top_20 = ['Keywords', 'cast', 'crew', 'character', 'production_companies', 'production_countries', 'spoken_languages']
for feature_name in features_choose_top_20:
    features_total = []
    for i in range(train.shape[0]):
        features = train.iloc[i][feature_name]
        if type(features) == list:
            for feature in features:
                if feature not in features_total:
                    features_total.append(feature)
    for i in range(test.shape[0]):
        features = test.iloc[i][feature_name]
        if type(features) == list:
            for feature in features:
                if feature not in features_total:
                    features_total.append(feature)
    print(feature_name)
    print(len(features_total))
    dict_features = {}
    for feature in features_total:
        dict_features[feature] = 0
    for i in range(train.shape[0]):
        features = train.iloc[i][feature_name]
        if type(features) == list:
            for feature in features:
                dict_features[feature] += 1
    for i in range(test.shape[0]):
        features = test.iloc[i][feature_name]
        if type(features) == list:
            for feature in features:
                dict_features[feature] += 1
    lis = sorted(dict_features.items(), key=lambda item: item[1], reverse = True)[:20]
    print(lis)
    for j in range(20):
        train[feature_name + '_' + lis[j][0]] = 0
    for i in range(train.shape[0]):
        for j in range(20):
            if type(train.iloc[i][feature_name]) == list:
                if lis[j][0] in train.iloc[i][feature_name]:
                    train[feature_name + '_' + lis[j][0]].iloc[i] = 1
    for j in range(20):
        test[feature_name + '_' + lis[j][0]] = 0
    for i in range(test.shape[0]):
        for j in range(20):
            if type(test.iloc[i][feature_name]) == list:
                if lis[j][0] in test.iloc[i][feature_name]:
                    test[feature_name + '_' + lis[j][0]].iloc[i] = 1
    train.drop(columns = [feature_name],inplace=True)
    test.drop(columns = [feature_name],inplace=True)

Keywords
11930
[('woman director', 457), ('independent film', 384), ('duringcreditsstinger', 350), ('based on novel', 312), ('murder', 305), ('violence', 245), ('love', 190), ('revenge', 188), ('sex', 186), ('aftercreditsstinger', 183), ('biography', 176), ('sport', 175), ('friendship', 168), ('dystopia', 166), ('police', 160), ('suspense', 159), ('sequel', 158), ('nudity', 153), ('musical', 147), ('teenager', 145)]

C:\Users\xiaorui\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

cast
75944
[('Samuel L. Jackson', 80), ('Robert De Niro', 71), ('Bruce Willis', 62), ('Morgan Freeman', 61), ('Liam Neeson', 57), ('Willem Dafoe', 55), ('Steve Buscemi', 55), ('Sylvester Stallone', 54), ('Nicolas Cage', 54), ('Matt Damon', 51), ('J.K. Simmons', 50), ('John Goodman', 50), ('Julianne Moore', 50), ('Christopher Walken', 50), ('Robin Williams', 50), ('Johnny Depp', 48), ('Stanley Tucci', 47), ('Harrison Ford', 46), ('Richard Jenkins', 46), ('Ben Stiller', 46)]
crew
68763
[('Avy Kaufman', 105), ('Steven Spielberg', 104), ('Robert Rodriguez', 100), ('Mary Vernieu', 99), ('Deborah Aquila', 88), ('Bob Weinstein', 87), ('Harvey Weinstein', 86), ('Hans Zimmer', 83), ('Tricia Wood', 83), ('James Newton Howard', 81), ('James Horner', 79), ('Luc Besson', 77), ('Francine Maisler', 75), ('Kerry Barden', 74), ('Jerry Goldsmith', 72), ('John Williams', 71), ('Danny Elfman', 67), ('Alan Silvestri', 67), ('Billy Hopkins', 65), ('Suzanne Smith', 63)]
character
102052
[('', 1828), ('Himself', 1497), ('Herself', 388), ('Dancer', 385), ('Additional Voices (voice)', 335), ('Doctor', 202), ('Reporter', 201), ('Nurse', 171), ('Waitress', 144), ('Bartender', 142), ('Priest', 113), ('Soldier', 113), ('Security Guard', 109), ('(uncredited)', 109), ('Cop', 108), ('Paul', 108), ('Jack', 106), ('Frank', 104), ('Sam', 102), ('Charlie', 101)]
production_companies
7087
[('Warner Bros.', 491), ('Universal Pictures', 463), ('Paramount Pictures', 393), ('Twentieth Century Fox Film Corporation', 341), ('Columbia Pictures', 236), ('Metro-Goldwyn-Mayer (MGM)', 207), ('New Line Cinema', 198), ('Touchstone Pictures', 158), ('Walt Disney Pictures', 147), ('Columbia Pictures Corporation', 140), ('Canal+', 130), ('TriStar Pictures', 121), ('Relativity Media', 115), ('United Artists', 105), ('Miramax Films', 104), ('Village Roadshow Pictures', 89), ('Regency Enterprises', 81), ('DreamWorks SKG', 78), ('Fox Searchlight Pictures', 69), ('Amblin Entertainment', 68)]
production_countries
98
[('US', 5617), ('GB', 917), ('FR', 570), ('DE', 411), ('CA', 323), ('IN', 220), ('IT', 160), ('JP', 157), ('AU', 148), ('ES', 139), ('RU', 132), ('CN', 99), ('HK', 96), ('BE', 64), ('IE', 62), ('KR', 58), ('SE', 50), ('MX', 44), ('NL', 43), ('DK', 40)]
spoken_languages
98
[('en', 6449), ('fr', 711), ('es', 559), ('de', 419), ('ru', 364), ('it', 321), ('ja', 204), ('zh', 163), ('hi', 160), ('ar', 102), ('pt', 100), ('cn', 89), ('ko', 78), ('pl', 69), ('la', 66), ('hu', 64), ('cs', 57), ('th', 55), ('ta', 52), ('sv', 50)]

In [ ]:
train

,budget,genres,original_language,popularity,runtime,status,days_since_release,weekday,day,month,...,spoken_languages_pt,spoken_languages_cn,spoken_languages_ko,spoken_languages_pl,spoken_languages_la,spoken_languages_hu,spoken_languages_cs,spoken_languages_th,spoken_languages_ta,spoken_languages_sv
0,16.454568,[Comedy],en,6.575393,93.0,Released,1776,4,20,2,...,0,0,0,0,0,0,0,0,0,0
1,17.504390,"[Comedy, Drama, Family, Romance]",en,8.248895,113.0,Released,5626,4,6,8,...,0,0,0,0,0,0,0,0,0,0
2,15.009433,[Drama],en,64.299990,105.0,Released,1909,4,10,10,...,0,0,0,0,0,0,0,0,0,0
3,13.997832,"[Thriller, Drama]",hi,3.174936,122.0,Released,2854,4,9,3,...,0,0,0,0,0,0,0,0,0,0
4,16.284763,"[Action, Thriller]",ko,1.148070,118.0,Released,3982,3,5,2,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,16.284763,"[Comedy, Romance]",en,9.853270,102.0,Released,9385,4,22,4,...,0,0,0,0,0,0,0,0,0,0
2996,16.284763,"[Drama, Music]",sv,3.727996,102.0,Released,2470,3,28,3,...,0,0,0,0,0,0,0,0,0,1
2997,17.989898,"[Crime, Action, Mystery, Thriller]",en,14.482345,120.0,Released,8482,4,11,10,...,0,0,0,0,0,0,0,0,0,0
2998,17.553180,"[Comedy, Romance]",en,15.725542,90.0,Released,5829,4,16,1,...,0,0,0,0,0,0,0,0,0,0
2999,17.370859,"[Thriller, Action, Mystery]",en,10.512109,106.0,Released,3023,3,22,9,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
test

,budget,genres,original_language,popularity,runtime,status,days_since_release,weekday,day,month,...,spoken_languages_pt,spoken_languages_cn,spoken_languages_ko,spoken_languages_pl,spoken_languages_la,spoken_languages_hu,spoken_languages_cs,spoken_languages_th,spoken_languages_ta,spoken_languages_sv
0,16.256171,"[Adventure, Animation, Family, Fantasy]",ja,3.851534,90.0,Released,4554.0,5.0,14.0,7.0,...,0,0,0,0,0,0,0,0,0,0
1,11.385092,"[Horror, Science Fiction]",en,3.559789,65.0,Released,22507.0,0.0,19.0,5.0,...,0,0,0,0,0,0,0,0,0,0
2,16.256171,"[Comedy, Romance]",en,8.085194,100.0,Released,8258.0,4.0,23.0,5.0,...,0,0,0,0,0,0,0,0,0,0
3,15.732433,"[Drama, War, Mystery]",fr,8.596012,130.0,Released,3406.0,5.0,4.0,9.0,...,0,0,0,0,0,0,0,0,0,0
4,14.508658,"[History, Documentary]",en,3.217680,92.0,Released,5437.0,4.0,11.0,2.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4393,17.553180,[Thriller],en,9.970359,118.0,Released,6725.0,4.0,3.0,8.0,...,0,0,0,0,1,0,0,0,0,0
4394,16.759950,"[Action, Adventure, Comedy, Thriller]",en,6.046516,95.0,Released,5612.0,4.0,20.0,8.0,...,0,0,0,0,0,0,0,0,0,0
4395,16.588099,[Drama],en,9.596883,129.0,Released,13538.0,2.0,8.0,12.0,...,0,0,0,0,0,0,0,0,0,0
4396,14.508658,"[Horror, Thriller]",en,20.359336,100.0,Released,1792.0,2.0,4.0,2.0,...,0,0,0,0,0,0,0,0,0,0
4397,11.066638,[Drama],fr,11.305910,85.0,Released,20922.0,3.0,20.0,9.0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
from sklearn.preprocessing import OneHotEncoder

single_category = ['original_language', 'status']
for feature_name in single_category:
    ohe = OneHotEncoder(handle_unknown='ignore')
    train_transformed = ohe.fit_transform(np.array(train[feature_name]).reshape(-1,1)).toarray()
    test_transformed = ohe.transform(np.array(test[feature_name]).reshape(-1,1)).toarray()

    train_data = pd.DataFrame(train_transformed,columns=ohe.get_feature_names_out())
    test_data = pd.DataFrame(test_transformed,columns=ohe.get_feature_names_out())

    train = pd.concat([train, train_data], axis = 1)
    test = pd.concat([test, test_data], axis = 1)
    
    train.drop(columns = [feature_name],inplace=True)
    test.drop(columns = [feature_name],inplace=True)

In [ ]:
train

,budget,genres,popularity,runtime,days_since_release,weekday,day,month,year,no_genres,...,x0_sr,x0_sv,x0_ta,x0_te,x0_tr,x0_ur,x0_vi,x0_zh,x0_Released,x0_Rumored
0,16.454568,[Comedy],6.575393,93.0,1776,4,20,2,2015,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,17.504390,"[Comedy, Drama, Family, Romance]",8.248895,113.0,5626,4,6,8,2004,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,15.009433,[Drama],64.299990,105.0,1909,4,10,10,2014,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,13.997832,"[Thriller, Drama]",3.174936,122.0,2854,4,9,3,2012,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,16.284763,"[Action, Thriller]",1.148070,118.0,3982,3,5,2,2009,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,16.284763,"[Comedy, Romance]",9.853270,102.0,9385,4,22,4,1994,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2996,16.284763,"[Drama, Music]",3.727996,102.0,2470,3,28,3,2013,2,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2997,17.989898,"[Crime, Action, Mystery, Thriller]",14.482345,120.0,8482,4,11,10,1996,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2998,17.553180,"[Comedy, Romance]",15.725542,90.0,5829,4,16,1,2004,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2999,17.370859,"[Thriller, Action, Mystery]",10.512109,106.0,3023,3,22,9,2011,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
test

,budget,genres,popularity,runtime,days_since_release,weekday,day,month,year,no_genres,...,x0_sr,x0_sv,x0_ta,x0_te,x0_tr,x0_ur,x0_vi,x0_zh,x0_Released,x0_Rumored
0,16.256171,"[Adventure, Animation, Family, Fantasy]",3.851534,90.0,4554.0,5.0,14.0,7.0,2007.0,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,11.385092,"[Horror, Science Fiction]",3.559789,65.0,22507.0,0.0,19.0,5.0,1958.0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,16.256171,"[Comedy, Romance]",8.085194,100.0,8258.0,4.0,23.0,5.0,1997.0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,15.732433,"[Drama, War, Mystery]",8.596012,130.0,3406.0,5.0,4.0,9.0,2010.0,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,14.508658,"[History, Documentary]",3.217680,92.0,5437.0,4.0,11.0,2.0,2005.0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4393,17.553180,[Thriller],9.970359,118.0,6725.0,4.0,3.0,8.0,2001.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4394,16.759950,"[Action, Adventure, Comedy, Thriller]",6.046516,95.0,5612.0,4.0,20.0,8.0,2004.0,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4395,16.588099,[Drama],9.596883,129.0,13538.0,2.0,8.0,12.0,1982.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4396,14.508658,"[Horror, Thriller]",20.359336,100.0,1792.0,2.0,4.0,2.0,2015.0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4397,11.066638,[Drama],11.305910,85.0,20922.0,3.0,20.0,9.0,1962.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
several_category = ['genres']

for feature_name in several_category:
    features_total = []
    for i in range(train.shape[0]):
        features = train.iloc[i][feature_name]
        if type(features) == list:
            for feature in features:
                if feature not in features_total:
                    features_total.append(feature)
    for i in range(test.shape[0]):
        features = test.iloc[i][feature_name]
        if type(features) == list:
            for feature in features:
                if feature not in features_total:
                    features_total.append(feature)
    print(feature_name)
    print(len(features_total))
    
    for j in range(len(features_total)):
        train[feature_name + '_' + features_total[j]] = 0
    for i in range(train.shape[0]):
        for j in range(len(features_total)):
            if type(train.iloc[i][feature_name]) == list:
                if features_total[j] in train.iloc[i][feature_name]:
                    train[feature_name + '_' + features_total[j]].iloc[i] = 1
    for j in range(len(features_total)):
        test[feature_name + '_' + features_total[j]] = 0
    for i in range(test.shape[0]):
        for j in range(len(features_total)):
            if type(test.iloc[i][feature_name]) == list:
                if features_total[j] in test.iloc[i][feature_name]:
                    test[feature_name + '_' + features_total[j]].iloc[i] = 1
    train.drop(columns = [feature_name],inplace=True)
    test.drop(columns = [feature_name],inplace=True)

genres
20

C:\Users\xiaorui\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [ ]:
train

,budget,popularity,runtime,days_since_release,weekday,day,month,year,no_genres,no_companies,...,genres_Music,genres_Crime,genres_Science Fiction,genres_Mystery,genres_Foreign,genres_Fantasy,genres_War,genres_Western,genres_History,genres_TV Movie
0,16.454568,6.575393,93.0,1776,4,20,2,2015,1,3,...,0,0,0,0,0,0,0,0,0,0
1,17.504390,8.248895,113.0,5626,4,6,8,2004,4,1,...,0,0,0,0,0,0,0,0,0,0
2,15.009433,64.299990,105.0,1909,4,10,10,2014,1,3,...,0,0,0,0,0,0,0,0,0,0
3,13.997832,3.174936,122.0,2854,4,9,3,2012,2,0,...,0,0,0,0,0,0,0,0,0,0
4,16.284763,1.148070,118.0,3982,3,5,2,2009,2,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,16.284763,9.853270,102.0,9385,4,22,4,1994,2,2,...,0,0,0,0,0,0,0,0,0,0
2996,16.284763,3.727996,102.0,2470,3,28,3,2013,2,2,...,1,0,0,0,0,0,0,0,0,0
2997,17.989898,14.482345,120.0,8482,4,11,10,1996,4,3,...,0,1,0,1,0,0,0,0,0,0
2998,17.553180,15.725542,90.0,5829,4,16,1,2004,2,2,...,0,0,0,0,0,0,0,0,0,0
2999,17.370859,10.512109,106.0,3023,3,22,9,2011,3,6,...,0,0,0,1,0,0,0,0,0,0

In [ ]:
test

,budget,popularity,runtime,days_since_release,weekday,day,month,year,no_genres,no_companies,...,genres_Music,genres_Crime,genres_Science Fiction,genres_Mystery,genres_Foreign,genres_Fantasy,genres_War,genres_Western,genres_History,genres_TV Movie
0,16.256171,3.851534,90.0,4554.0,5.0,14.0,7.0,2007.0,4,0,...,0,0,0,0,0,1,0,0,0,0
1,11.385092,3.559789,65.0,22507.0,0.0,19.0,5.0,1958.0,2,1,...,0,0,1,0,0,0,0,0,0,0
2,16.256171,8.085194,100.0,8258.0,4.0,23.0,5.0,1997.0,2,3,...,0,0,0,0,0,0,0,0,0,0
3,15.732433,8.596012,130.0,3406.0,5.0,4.0,9.0,2010.0,3,3,...,0,0,0,1,0,0,1,0,0,0
4,14.508658,3.217680,92.0,5437.0,4.0,11.0,2.0,2005.0,2,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4393,17.553180,9.970359,118.0,6725.0,4.0,3.0,8.0,2001.0,1,7,...,0,0,0,0,0,0,0,0,0,0
4394,16.759950,6.046516,95.0,5612.0,4.0,20.0,8.0,2004.0,4,2,...,0,0,0,0,0,0,0,0,0,0
4395,16.588099,9.596883,129.0,13538.0,2.0,8.0,12.0,1982.0,1,1,...,0,0,0,0,0,0,0,0,0,0
4396,14.508658,20.359336,100.0,1792.0,2.0,4.0,2.0,2015.0,2,3,...,0,0,0,0,0,0,0,0,0,0
4397,11.066638,11.305910,85.0,20922.0,3.0,20.0,9.0,1962.0,1,3,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
train.to_csv('processed_train.csv')
test.to_csv('processed_test.csv')

In [ ]:
train = pd.read_csv('processed_train.csv')
train.drop(columns = ['Unnamed: 0'], inplace = True)
test = pd.read_csv('processed_test.csv')
test.drop(columns = ['Unnamed: 0'], inplace = True)
df = pd.read_csv('train.csv')
y = df.revenue.apply(lambda x: np.log(x))

In [ ]:
train.weekday = train.weekday.fillna(train.weekday.value_counts().index[0]).astype(int).astype('category')
train.day = train.day.fillna(train.day.value_counts().index[0]).astype(int).astype('category')
train.month = train.month.fillna(train.month.value_counts().index[0]).astype(int).astype('category')
test.weekday = test.weekday.fillna(test.weekday.value_counts().index[0]).astype(int).astype('category')
test.day = test.day.fillna(test.day.value_counts().index[0]).astype(int).astype('category')
test.month = test.month.fillna(test.month.value_counts().index[0]).astype(int).astype('category')